### ISSUE TITLE
Escape sequences not behaving correctly

### ISSUE THREAD

**Issue by jkwchui** [ityonemo/pegasus#3]
I'm not sure Pegasus is handling escape sequences correctly.  I am testing this with a single rule, where I use quotes `""` to designate a single character.

```
# grammar
test  <- "\?"

# using the parser
parse("?")
> ["?"] 
```

This behaves correct with the `\?` escape sequence.  However, 

```
# grammar, with the \nnn octal form
test  <- "\065" 
```

fails to compile with a FunctionClauseError, and perhaps most surprisingly,

```
# grammar
test  <- "\65"
```

does compile, but it matches `"65"` instead of interpreting the escape sequence.

```
# using the parser
parse("65")
> ["65"] 

parse("A")
> ** (MatchError) no match of right hand side value: {:error, "expected string \"65\"", "A", %{}, {1, 0}, 0}
```

This limitation blocks byte-by-byte matching, and thus access to Unicode characters.

**Comment by ityonemo** [comment]
heh, thanks, I couldn't figure out what I'd messed up here:  https://github.com/ityonemo/pegasus/issues/1, thanks for the repro

**Comment by ityonemo** [comment]
a3ae664

**Comment by jkwchui** [comment]
I don't think this is a closed issue?  https://github.com/ityonemo/pegasus/commit/a3ae6640f4c50c4a459a7ff35dac5a0c2d7193b9 adds a comment to post-traversal, but the behaviour described in https://github.com/ityonemo/pegasus/issues/3#issue-2126796644 remains unchanged, and thus byte-by-byte matching / accessing Unicode characters still remains out of reach of Pegasus.
